struct GidsFileSystem<_CARD_DATA *>
{
	static GidsFileSystem<_CARD_DATA *> * CreateInstance(void * (*)(unsigned __int64),void (*)(void *),unsigned long (*)(_CARD_DATA *,unsigned short,unsigned long,unsigned char * *,unsigned long *,int),unsigned long (*)(_CARD_DATA *,unsigned short,unsigned long,unsigned char *,unsigned long,int),_CARD_DATA *);
};

namespace SafeIntInternal
{
	struct SafeIntExceptionHandler<SafeIntWin32Exception>
	{
		static void SafeIntOnOverflow();
	};

};

char * WPP_pszIndent;
int I_IsValidFilename(char *,unsigned __int64,int);
int I_IsValidPIVCertFileTag(unsigned long);
int I_IsValidPIVKeyID(unsigned char);
long StringCbCatA(char *,unsigned __int64,char const *);
long StringCbPrintfA(char *,unsigned __int64,char const *,...);
long StringCbPrintfW(unsigned short *,unsigned __int64,unsigned short const *,...);
long StringCchPrintfW(unsigned short *,unsigned __int64,unsigned short const *,...);
unsigned long CardAcquireContext(_CARD_DATA *,unsigned long);
unsigned long CardAcquireContextInternal(_CARD_DATA *,unsigned long);
unsigned long CardAuthenticateChallenge(_CARD_DATA *,unsigned char *,unsigned long,unsigned long *);
unsigned long CardAuthenticateEx(_CARD_DATA *,unsigned long,unsigned long,unsigned char *,unsigned long,unsigned char * *,unsigned long *,unsigned long *);
unsigned long CardAuthenticatePin(_CARD_DATA *,unsigned short *,unsigned char *,unsigned long,unsigned long *);
unsigned long CardChangeAuthenticator(_CARD_DATA *,unsigned short *,unsigned char *,unsigned long,unsigned char *,unsigned long,unsigned long,unsigned long,unsigned long *);
unsigned long CardChangeAuthenticatorEx(_CARD_DATA *,unsigned long,unsigned long,unsigned char *,unsigned long,unsigned long,unsigned char *,unsigned long,unsigned long,unsigned long *);
unsigned long CardCreateClaim(_CARD_DATA_INTERNAL *,_CARD_ATTESTATION_CLAIM_INFO *);
unsigned long CardCreateContainer(_CARD_DATA *,unsigned char,unsigned long,unsigned long,unsigned long,unsigned char *);
unsigned long CardCreateContainerEx(_CARD_DATA *,unsigned char,unsigned long,unsigned long,unsigned long,unsigned char *,unsigned long);
unsigned long CardCreateDirectory(_CARD_DATA *,char *,CARD_DIRECTORY_ACCESS_CONDITION);
unsigned long CardCreateFile(_CARD_DATA *,char *,char *,unsigned long,CARD_FILE_ACCESS_CONDITION);
unsigned long CardDeauthenticateEx(_CARD_DATA *,unsigned long,unsigned long);
unsigned long CardDeleteContainer(_CARD_DATA *,unsigned char,unsigned long);
unsigned long CardDeleteContext(_CARD_DATA *);
unsigned long CardDeleteDirectory(_CARD_DATA *,char *);
unsigned long CardDeleteFile(_CARD_DATA *,char *,char *,unsigned long);
unsigned long CardDestroyKey(_CARD_DATA *,unsigned __int64);
unsigned long CardEnumFiles(_CARD_DATA *,char *,char * *,unsigned long *,unsigned long);
unsigned long CardGetAikCertificate(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long CardGetAikContainerInfo(_CARD_DATA *,_AIK_CONTAINER_INFO *);
unsigned long CardGetAikContainerName(_CARD_DATA *,unsigned short * *);
unsigned long CardGetAlgorithmProperty(_CARD_DATA *,unsigned short const *,unsigned short const *,unsigned char *,unsigned long,unsigned long *,unsigned long);
unsigned long CardGetChallenge(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long CardGetChallengeEx(_CARD_DATA *,unsigned long,unsigned char * *,unsigned long *,unsigned long);
unsigned long CardGetContainerInfo(_CARD_DATA *,unsigned char,unsigned long,_CONTAINER_INFO *);
unsigned long CardGetContainerProperty(_CARD_DATA *,unsigned char,unsigned short const *,unsigned char *,unsigned long,unsigned long *,unsigned long);
unsigned long CardGetFileInfo(_CARD_DATA *,char *,char *,_CARD_FILE_INFO *);
unsigned long CardGetKeyProperty(_CARD_DATA *,unsigned __int64,unsigned short const *,unsigned char *,unsigned long,unsigned long *,unsigned long);
unsigned long CardGetProperty(_CARD_DATA *,unsigned short const *,unsigned char *,unsigned long,unsigned long *,unsigned long);
unsigned long CardGetSharedKeyHandle(_CARD_DATA *,unsigned char *,unsigned long,unsigned char * *,unsigned long *,unsigned __int64 *);
unsigned long CardImportSessionKey(_CARD_DATA *,unsigned char,void *,unsigned short const *,unsigned short const *,unsigned __int64 *,unsigned char *,unsigned long,unsigned long);
unsigned long CardProcessEncryptedData(_CARD_DATA *,unsigned __int64,unsigned short const *,_CARD_ENCRYPTED_DATA *,unsigned long,unsigned char *,unsigned long,unsigned long *,unsigned long);
unsigned long CardQueryCapabilities(_CARD_DATA *,_CARD_CAPABILITIES *);
unsigned long CardQueryFreeSpace(_CARD_DATA *,unsigned long,_CARD_FREE_SPACE_INFO *);
unsigned long CardQueryKeySizes(_CARD_DATA *,unsigned long,unsigned long,_CARD_KEY_SIZES *);
unsigned long CardRSADecrypt(_CARD_DATA *,_CARD_RSA_DECRYPT_INFO *);
unsigned long CardReadFile(_CARD_DATA *,char *,char *,unsigned long,unsigned char * *,unsigned long *);
unsigned long CardSetContainerProperty(_CARD_DATA *,unsigned char,unsigned short const *,unsigned char *,unsigned long,unsigned long);
unsigned long CardSetKeyProperty(_CARD_DATA *,unsigned __int64,unsigned short const *,unsigned char *,unsigned long,unsigned long);
unsigned long CardSetProperty(_CARD_DATA *,unsigned short const *,unsigned char *,unsigned long,unsigned long);
unsigned long CardSignData(_CARD_DATA *,_CARD_SIGNING_INFO *);
unsigned long CardUnblockPin(_CARD_DATA *,unsigned short *,unsigned char *,unsigned long,unsigned char *,unsigned long,unsigned long,unsigned long);
unsigned long CardWriteFile(_CARD_DATA *,char *,char *,unsigned long,unsigned char *,unsigned long);
unsigned long I_AuthenticateChallenge(_CARD_DATA *,unsigned char *,unsigned long,unsigned long *);
unsigned long I_AuthenticatePin(_CARD_DATA *,unsigned char,unsigned char *,unsigned long,unsigned long *);
unsigned long I_Calculate3DESKeyCheckValue(_CARD_DATA *,unsigned char *,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_CalculateSizeOfTag(unsigned long,unsigned char *);
unsigned long I_CalculateSizeOfValue(unsigned long,unsigned char *);
unsigned long I_ChallengeResponseUnblockPin(_CARD_DATA *,unsigned char,unsigned char *,unsigned long);
unsigned long I_ChangePin(_CARD_DATA *,unsigned char,unsigned char *,unsigned long,unsigned char *,unsigned long,unsigned long *);
unsigned long I_ClmdCmdExtendedTransmit(_CARD_DATA *,unsigned char,unsigned char,unsigned char,unsigned char,unsigned char *,unsigned long,unsigned char * *,unsigned long *,unsigned short *,int);
unsigned long I_ClmdCmdParseReturnData(_CARD_DATA *,unsigned char *,unsigned long,unsigned short *,unsigned char * *,unsigned long *);
unsigned long I_ClmdCmdShortTransmit(_CARD_DATA *,unsigned char,unsigned char,unsigned char,unsigned char,unsigned char *,unsigned long,unsigned char * *,unsigned long *,unsigned short *,int);
unsigned long I_ClmdCmdTransmit(_CARD_DATA *,unsigned char,unsigned char,unsigned char,unsigned char,unsigned char *,unsigned long,unsigned char * *,unsigned long *,unsigned short *,int);
unsigned long I_ConstructPublicKeyBlob(_CARD_DATA *,unsigned int,unsigned char *,unsigned long,unsigned char *,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_CreateAndActivateKeyFile(_CARD_DATA *,_CLMD_KEY_CONTAINER_ENTRY *);
unsigned long I_CreateButterflyFileOrDirectory(_CARD_DATA *,char *,char *,unsigned short,unsigned long);
unsigned long I_CreateGIDSClaim(_CARD_DATA *,unsigned char,unsigned char,unsigned char *,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_Deauthenticate(_CARD_DATA *);
unsigned long I_DecodeCertificate(_CARD_DATA *,unsigned char *,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_DeleteButterflyFileOrDirectory(_CARD_DATA *,char *,char *);
unsigned long I_DeleteElementaryFile(_CARD_DATA *,unsigned short);
unsigned long I_EnumButterflyFiles(_CARD_DATA *,char *,char * *,unsigned long *);
unsigned long I_EnumPIVFiles(_CARD_DATA *,char *,char * *,unsigned long *);
unsigned long I_ExtractData(_CARD_DATA *,unsigned char *,unsigned long,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_FsDeleteFilesystemTable<_CARD_DATA *>(GidsFileSystem<_CARD_DATA *> *);
unsigned long I_FsFindEntry(_CLMD_FILESYSTEM_ENTRY *,unsigned long,char *,char *,unsigned long *);
unsigned long I_FsGetAvailableEntry<_CARD_DATA *>(GidsFileSystem<_CARD_DATA *> *,_CLMD_FILESYSTEM_ENTRY * *,unsigned long *,char *,char *,unsigned short,unsigned long *);
unsigned long I_FsGetEntriesInDirectory<_CARD_DATA *>(GidsFileSystem<_CARD_DATA *> *,char *,_CLMD_FILESYSTEM_ENTRY * *,unsigned long *);
unsigned long I_FsGetFilesystemTable<_CARD_DATA *>(GidsFileSystem<_CARD_DATA *> *,_CLMD_FILESYSTEM_ENTRY * *,unsigned long *);
unsigned long I_FsUpdateFilesystemTable<_CARD_DATA *>(GidsFileSystem<_CARD_DATA *> *,_CLMD_FILESYSTEM_ENTRY *,unsigned long);
unsigned long I_GICSCardRSADecrypt(_CARD_DATA *,_CARD_RSA_DECRYPT_INFO *);
unsigned long I_GICSCardSignData(_CARD_DATA *,_CARD_SIGNING_INFO *);
unsigned long I_GIDS_InitializeVendorSpecific(_CARD_DATA *);
unsigned long I_GUIDToString(_CARD_DATA *,_GUID *,unsigned short * *);
unsigned long I_GenerateFullPinBuffer(_CARD_DATA *,unsigned char *,unsigned long,unsigned char *,unsigned long,unsigned char * *,unsigned long *,unsigned char *);
unsigned long I_GenerateGICSAsymmetricKeyPair(_CARD_DATA *,_CLMD_KEY_CONTAINER_ENTRY *);
unsigned long I_GenerateKeyFileCRTs(_CARD_DATA *,_CRT_RECORD *,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_GenerateKeyFileFCP(_CARD_DATA *,_CLMD_KEY_CONTAINER_ENTRY *,unsigned char * *,unsigned long *);
unsigned long I_GeneratePIVAsymmetricKeyPair(_CARD_DATA *,_CLMD_PIV_GENERATE_ASYMMETRIC_KEY *,unsigned char * *,unsigned long *);
unsigned long I_GeneratePinBuffer(_CARD_DATA *,unsigned char *,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_GenerateR1AndZ1(_CARD_DATA *,unsigned char * *,unsigned long *,unsigned char * *,unsigned long *);
unsigned long I_GetActiveProtocol(_CARD_DATA *,unsigned long *);
unsigned long I_GetButterflyContainer(_CARD_DATA *,unsigned char,_CLMD_KEY_CONTAINER_ENTRY *);
unsigned long I_GetButterflyFileInformation(_CARD_DATA *,char *,char *,_CARD_FILE_INFO *);
unsigned long I_GetButterflyFileLocation(_CARD_DATA *,char *,char *,unsigned short *,unsigned long *);
unsigned long I_GetButterflyPublicKey(_CARD_DATA *,unsigned char,_CONTAINER_INFO *);
unsigned long I_GetCardActivityCount(_CARD_DATA *,unsigned short *,unsigned short *);
unsigned long I_GetCardType(_CARD_DATA *,unsigned long *);
unsigned long I_GetChallengeStatus(_CARD_DATA *,int *);
unsigned long I_GetContainerInfo(_CARD_DATA *,unsigned char,_CONTAINER_INFO *);
unsigned long I_GetContainerMapRecords(_CARD_DATA *,_CONTAINER_MAP_RECORD * *,unsigned long *);
unsigned long I_GetData(_CARD_DATA *,unsigned short,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_GetFileCache(_CARD_DATA *,unsigned long,unsigned char * *,unsigned long *);
unsigned long I_GetFreeSpace(_CARD_DATA *,_CARD_FREE_SPACE_INFO *);
unsigned long I_GetGIDSAikCertificate(_CARD_DATA *,unsigned char,unsigned char * *,unsigned long *);
unsigned long I_GetGIDSAikContainerName(_CARD_DATA *,unsigned char,unsigned short * *);
unsigned long I_GetGIDSChallenge(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long I_GetGIDSExternalAuthChallenge(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long I_GetGIDSMutualAuthChallenge(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long I_GetGIDSVendorSpecific(_CARD_DATA *,_CLMD_GIDS_CARD_DATA * *);
unsigned long I_GetInitDeferredPIVCMapFile(_CARD_DATA *,_CONTAINER_MAP_RECORD * *,unsigned long *);
unsigned long I_GetInitDeferredPIVMscpDirectory(_CARD_DATA *,char * *,unsigned long *);
unsigned long I_GetKeyAndAlgFromMapIndex(_CARD_DATA *,unsigned char,unsigned char *,unsigned char *,unsigned long *);
unsigned long I_GetKeyClassAndAlgIdFromKeySpecAndKeySize(unsigned long,unsigned long,unsigned char *,unsigned char *);
unsigned long I_GetKeySizes(_CARD_DATA *,unsigned char *,unsigned long,unsigned long);
unsigned long I_GetPIVCMapFile(_CARD_DATA *,_CONTAINER_MAP_RECORD * *,unsigned long *);
unsigned long I_GetPIVCache(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long I_GetPIVCachedFreshnessCounter(_CARD_DATA *,unsigned long,unsigned short *);
unsigned long I_GetPIVCardApps(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long I_GetPIVCardId(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long I_GetPIVCertFileTagFromPIVKeyID(unsigned char,unsigned long *);
unsigned long I_GetPIVChallenge(_CARD_DATA *,unsigned char * *,unsigned long *);
unsigned long I_GetPIVContainer(_CARD_DATA *,unsigned char,_CONTAINER_MAP_RECORD *);
unsigned long I_GetPIVContainerInfoFromTag(_CARD_DATA *,unsigned long,_CONTAINER_INFO *);
unsigned long I_GetPIVFileInformation(_CARD_DATA *,char *,char *,_CARD_FILE_INFO *);
unsigned long I_GetPIVFileTag(_CARD_DATA *,char *,unsigned long *);
unsigned long I_GetPIVItemFromGlobalCache(_CARD_DATA *,unsigned short *,unsigned char * *,unsigned long *,int);
unsigned long I_GetPIVKeyHistory(_CARD_DATA *,unsigned long *);
unsigned long I_GetPIVKeyIDFromPIVCertFileTag(unsigned long,unsigned char *);
unsigned long I_GetPIVMscpDirectory(_CARD_DATA *,char * *,unsigned long *);
unsigned long I_GetPIVPublicKey(_CARD_DATA *,unsigned char,unsigned char * *,unsigned long *);
unsigned long I_GetPinInfoProperty(_CARD_DATA *,_PIN_INFO *,unsigned long);
unsigned long I_GetPublicKey(_CARD_DATA *,unsigned char,unsigned char * *,unsigned long *,unsigned char * *,unsigned long *);
unsigned long I_GetReadOnlyProperty(_CARD_DATA *,int *);
unsigned long I_GetReaderName(_CARD_DATA *,unsigned short * *);
unsigned long I_GetRemainingAttempts(unsigned long,unsigned short,unsigned long *);
unsigned long I_GetVendorSpecific(_CARD_DATA *,_CLMD_CARD_DATA * *);
unsigned long I_HexToString(_CARD_DATA *,unsigned long,unsigned short * *);
unsigned long I_ImportGIDSAsymmetricKey(_CARD_DATA *,unsigned char *,unsigned long,_CLMD_KEY_CONTAINER_ENTRY *);
unsigned long I_ImportGIDSSymmetricKey(_CARD_DATA *,unsigned char,unsigned char *,unsigned long,unsigned char *,unsigned long);
unsigned long I_IncrementPIVFreshnessCounter(_CARD_DATA *,unsigned long);
unsigned long I_InitializePIVCardId(_CARD_DATA *);
unsigned long I_InitializePIVContainerInfo(_CARD_DATA *);
unsigned long I_InitializePIVGlobalCacheLookupParameters(_CARD_DATA *,unsigned short *,unsigned char * *,unsigned long *,unsigned short * *,unsigned long *);
unsigned long I_InitializeSinglePIVContainerMapRecordFromContainerInfo(_CARD_DATA *,_CONTAINER_MAP_RECORD * *,unsigned short *,unsigned long,unsigned char,_CONTAINER_INFO *);
unsigned long I_InitializeSinglePIVContainerMapRecordFromTag(_CARD_DATA *,unsigned short *,unsigned long,unsigned char,_CONTAINER_MAP_RECORD * *);
unsigned long I_KeyMgrCreateContainer(_CARD_DATA *,unsigned char,unsigned char,unsigned char,unsigned long,unsigned char *,unsigned long);
unsigned long I_KeyMgrDeleteContainer(_CARD_DATA *,unsigned char);
unsigned long I_KeyMgrDeleteTable(_CARD_DATA *);
unsigned long I_KeyMgrGetTable(_CARD_DATA *,_CLMD_KEY_CONTAINER_ENTRY * *,unsigned long *);
unsigned long I_KeyMgrUpdateTable(_CARD_DATA *,_CLMD_KEY_CONTAINER_ENTRY *,unsigned long);
unsigned long I_ManageSecurityEnvironment(_CARD_DATA *,unsigned char,unsigned char,unsigned char,int);
unsigned long I_PIVCardRSADecrypt(_CARD_DATA *,_CARD_RSA_DECRYPT_INFO *);
unsigned long I_PIVCardSignData(_CARD_DATA *,_CARD_SIGNING_INFO *);
unsigned long I_PIV_InitializeVendorSpecific(_CARD_DATA *);
unsigned long I_PackData(_CARD_DATA *,unsigned long,unsigned char *,unsigned long,unsigned char * *,unsigned long *,_MULTI_TAG_RECORD *,unsigned long);
unsigned long I_PutData(_CARD_DATA *,unsigned short,unsigned char *,unsigned long);
unsigned long I_PutTagInBuffer(unsigned long,unsigned char,unsigned char *,unsigned long);
unsigned long I_PutValueLengthInBuffer(unsigned long,unsigned char,unsigned char *,unsigned long);
unsigned long I_ReadButterflyFile(_CARD_DATA *,char *,char *,unsigned char * *,unsigned long *);
unsigned long I_ReadFile(_CARD_DATA *,unsigned short,unsigned long,unsigned char * *,unsigned long *,int);
unsigned long I_ReadPIVFile(_CARD_DATA *,char *,char *,unsigned char * *,unsigned long *);
unsigned long I_ReverseData(unsigned char *,unsigned long);
unsigned long I_RouteReadFile(_CARD_DATA *,char *,char *,unsigned char * *,unsigned long *);
unsigned long I_SelectAID(_CARD_DATA *,unsigned char *,unsigned long,unsigned char * *,unsigned long *,int);
unsigned long I_SelectActiveApplication(_CARD_DATA *);
unsigned long I_SelectCompatibleSmartCardAID(_CARD_DATA *);
unsigned long I_SelectDF(_CARD_DATA *);
unsigned long I_SetActiveProtocol(_CARD_DATA *,unsigned long);
unsigned long I_SetCardType(_CARD_DATA *,unsigned long);
unsigned long I_SetChallengeStatus(_CARD_DATA *,int);
unsigned long I_SetExtendedAPDUSupport(_CARD_DATA *);
unsigned long I_SetFileCache(_CARD_DATA *,unsigned long,unsigned char *,unsigned long);
unsigned long I_SetPIVCMapFile(_CARD_DATA *,_CONTAINER_MAP_RECORD *,unsigned long);
unsigned long I_SetPIVCardId(_CARD_DATA *,unsigned char *,unsigned long);
unsigned long I_SetPIVItemInGlobalCache(_CARD_DATA *,unsigned short *,unsigned char *,unsigned long,int);
unsigned long I_SetPIVMscpDirectory(_CARD_DATA *,char *,unsigned long);
unsigned long I_SetPIVPublicKey(_CARD_DATA *,unsigned char,unsigned char *,unsigned long);
unsigned long I_SetReadOnlyProperty(_CARD_DATA *,int);
unsigned long I_SetReaderName(_CARD_DATA *,unsigned short *);
unsigned long I_SetVendorSpecific(_CARD_DATA *);
unsigned long I_TranslateAlgNameToAlgId(unsigned short const *,unsigned int *);
unsigned long I_TranslateStatusCode(unsigned short,int);
unsigned long I_UnblockPin(_CARD_DATA *,unsigned char,unsigned char *,unsigned long,unsigned char *,unsigned long,unsigned long *);
unsigned long I_VerifyAtr(unsigned char *,unsigned long);
unsigned long I_VerifySignaturePaddingAndHashAlg(_CARD_SIGNING_INFO *,unsigned int *);
unsigned long I_WriteFile(_CARD_DATA *,unsigned short,unsigned long,unsigned char *,unsigned long,int);
unsigned long MDEncryptData(_CARD_DATA *,unsigned __int64,unsigned short const *,unsigned char *,unsigned long,unsigned long,_CARD_ENCRYPTED_DATA * *,unsigned long *);
unsigned long MDImportSessionKey(_CARD_DATA *,unsigned short const *,unsigned short const *,unsigned __int64 *,unsigned char *,unsigned long);
unsigned short * * CachedPIVRetiredKeyMgmtKeys;
void I_FreeVendorSpecific(_CARD_DATA *);
void WppTraceIndent(char * *,_WppTraceIndentType);
